name: Server Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
  
        - name: Install dependencies
          run: npm install
  
        - name: Build server
          run: npm run build
  
        - name: Archive build artifacts
          uses: actions/upload-artifact@v3
          with:
            name: server-build
            path: dist/spa
#     steps:
#       - uses: actions/checkout@v2
#       - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
#         with:
#           heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#           heroku_app_name: "YOUR APP's NAME" #Must be unique in Heroku
#           heroku_email: "YOUR EMAIL"
